// src/pages/landing-page/HeroSection.vue
<template>
    <section id="landingHero" class="min-vh-100 d-flex align-items-center position-relative overflow-hidden bg-light">
        <!-- Background Animation -->
        <div class="hero-bg">
            <div class="gradient-blob blob-1"></div>
            <div class="gradient-blob blob-2"></div>
            <div class="gradient-blob blob-3"></div>
        </div>

        <div class="container position-relative">
            <div class="row align-items-center min-vh-100">
                <!-- Text Content -->
                <div class="col-lg-6 hero-content" data-aos="fade-up">
                    <!-- Title -->
                    <h1 class="hero-title" data-aos="fade-up" data-aos-delay="300">
                        
                        <span class="gradient-text">Nos solutions</span> adaptées
                        <br>pour votre
                        <span class="highlight-text"> organisation</span>
                    </h1>

                    <!-- Description -->
                    <p class="hero-description" data-aos="fade-up" data-aos-delay="400">
                        Découvrez comment ERP INNOV peut transformer votre activité. 
                        Que vous soyez entrepreneur individuel, TPE/PME en croissance, grande entreprise, association ou administration, nous vous offrons des solutions adaptées qui permettent :
                        <ul>
                            <li><b>Réduction des coûts opérationnels</b>: Optimisez vos dépenses et améliorez votre rentabilité.</li>
                            <li><b>Optimisation de la gestion</b>: Optimisez vos dépenses et améliorez votre rentabilité.</li>
                            <li><b>Croissance accélérée</b>: Adoptez des outils performants pour soutenir votre développement.</li>
                        </ul>
                    </p> 

                    <!-- CTA Buttons -->
                    <div class="hero-buttons" data-aos="fade-up" data-aos-delay="500">
                        <a href="/login" class="btn-primary">
                            <span>En savoir plus, inscription gratuite</span>
                            <i class="ri-arrow-right-line ms-2"></i>
                        </a>
                    </div>
                </div>

                <!-- Dashboard Preview -->
                <div class="col-lg-6 hero-dashboard" data-aos="fade-left" data-aos-delay="300">
                    <div class="dashboard-wrapper" ref="dashboardPreview">
                        <img src="/assets/img/front-pages/landing-page/hero-dashboard-light.png"
                             alt="Dashboard Preview"
                             class="dashboard-image">

                        <!-- Stats Cards -->
                        <div class="stats-card stats-card-1">
                            <div class="stats-indicator success"></div>
                            <span>+24% Croissance</span>
                        </div>

                        <div class="stats-card stats-card-2">
                            <div class="stats-indicator primary"></div>
                            <span>35% d'économies sur vos coûts</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</template>

<script>
import { onMounted, ref, onUnmounted } from 'vue'
import AOS from 'aos'
import 'aos/dist/aos.css'

export default {
    name: 'HeroSection',
    setup() {
        const dashboardPreview = ref(null)

        const handleMouseMove = (e) => {
            if (!dashboardPreview.value) return
            const { clientX, clientY } = e
            const { innerWidth, innerHeight } = window

            const x = (clientX - innerWidth / 2) / 25
            const y = (clientY - innerHeight / 2) / 25

            dashboardPreview.value.style.transform =
                `perspective(1000px) rotateY(${x}deg) rotateX(${-y}deg)`
        }

        onMounted(() => {
            AOS.init({
                duration: 1000,
                easing: 'ease-out',
                once: true
            })

            window.addEventListener('mousemove', handleMouseMove)
        })

        onUnmounted(() => {
            window.removeEventListener('mousemove', handleMouseMove)
        })

        return {
            dashboardPreview
        }
    }
}
</script>

<style scoped>
.hero-section {
    position: relative;
    overflow: hidden;
    background: #f8fafc;
    min-height: 100vh;
    padding: 6rem 0;
}

/* Background Animation */
.hero-bg {
    position: absolute;
    width: 100%;
    height: 100%;
    top: 0;
    left: 0;
    overflow: hidden;
}

.gradient-blob {
    position: absolute;
    border-radius: 50%;
    filter: blur(80px);
    opacity: 0.4;
    animation: float 20s ease-in-out infinite;
}

.blob-1 {
    width: 600px;
    height: 600px;
    background: linear-gradient(135deg, #60a5fa30, #3b82f630);
    top: -20%;
    left: -10%;
}

.blob-2 {
    width: 400px;
    height: 400px;
    background: linear-gradient(135deg, #818cf830, #6366f130);
    top: 40%;
    right: -5%;
    animation-delay: -5s;
}

.blob-3 {
    width: 300px;
    height: 300px;
    background: linear-gradient(135deg, #34d39930, #2563eb30);
    bottom: -10%;
    left: 50%;
    animation-delay: -10s;
}

/* Hero Content Styles */
.hero-content {
    position: relative;
    z-index: 2;
}

.hero-badge {
    display: inline-flex;
    align-items: center;
    padding: 0.5rem 1rem;
    background: linear-gradient(135deg, #3b82f610, #60a5fa10);
    border: 1px solid #60a5fa30;
    border-radius: 100px;
    font-weight: 500;
    color: #2563eb;
    margin-bottom: 2rem;
    transition: transform 0.3s ease;
}

.hero-badge:hover {
    transform: translateY(-2px);
}

.badge-icon {
    margin-right: 0.5rem;
}

.hero-title {
    font-size: 3.5rem;
    font-weight: 700;
    line-height: 1.2;
    margin-bottom: 1.5rem;
    margin-top: -10px;
    transition: font-size 0.3s ease;
}

.gradient-text {
    background: linear-gradient(135deg, #2563eb, #3b82f6);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
}

.highlight-text {
    color: #FF8C00;
}

.hero-description {
    font-size: 1.25rem;
    line-height: 1.7;
    color: #64748b;
    margin-bottom: 2.5rem;
}

/* Buttons */
.hero-buttons {
    display: flex;
    gap: 1rem;
}

.btn-primary, .btn-secondary {
    display: inline-flex;
    align-items: center;
    padding: 1rem 2rem;
    border-radius: 100px;
    font-weight: 500;
    transition: all 0.3s ease;
}

.btn-primary {
    background: linear-gradient(135deg, #2563eb, #3b82f6);
    color: white;
    box-shadow: 0 4px 12px rgba(37, 99, 235, 0.15);
}

.btn-secondary {
    background: white;
    color: #2563eb;
    border: 1px solid #60a5fa30;
}

.btn-primary:hover, .btn-secondary:hover {
    transform: translateY(-2px);
}

/* Dashboard Preview */
.dashboard-wrapper {
    position: relative;
    transition: transform 0.3s ease-out;
}

.dashboard-image {
    width: 100%;
    border-radius: 1rem;
    box-shadow: 0 20px 40px rgba(0, 0, 0, 0.1);
}

.stats-card {
    position: absolute;
    background: white;
    padding: 1rem 1.5rem;
    border-radius: 1rem;
    box-shadow: 0 8px 16px rgba(0, 0, 0, 0.1);
    display: flex;
    align-items: center;
    gap: 0.75rem;
    font-weight: 600;
    animation: float 6s ease-in-out infinite;
}

.stats-card-1 {
    top: 5%;
    right: -5%;
}

.stats-card-2 {
    bottom: 10%;
    left: -5%;
    animation-delay: -3s;
}

.stats-indicator {
    width: 10px;
    height: 10px;
    border-radius: 50%;
}

.success { background: #22c55e; }
.primary { background: #2563eb; }

@keyframes float {
    0%, 100% { transform: translateY(0); }
    50% { transform: translateY(-20px); }
}

/* Responsive Design */
@media (max-width: 992px) {
    .hero-title {
        font-size: 2.5rem;
    }

    .hero-content {
        text-align: center;
        margin-bottom: 3rem;
    }

    .hero-buttons {
        justify-content: center;
    }
}

/* Ultra larges (par exemple, écrans 4K ou ultra large) */
@media (min-width: 1920px) {
    .hero-title {
        font-size: 4.5rem; /* augmentation pour profiter de l'espace */
    }
}

/* Début écran de bureau standard (entre 1200px et 1919px) */
@media (max-width: 1919px) and (min-width: 1200px) {
    .hero-title {
        font-size: 3.5rem;
    }
}

/* Ecrans moyens ou Laptops (entre 992px et 1199px) */
@media (max-width: 1199px) and (min-width: 992px) {
    .hero-title {
        font-size: 3rem;
    }

    .hero-content {
        text-align: center;
        margin-bottom: 3rem;
    }

    .hero-buttons {
        justify-content: center;
    }
}

/* Tablettes (entre 768px et 991px) */
@media (max-width: 991px) and (min-width: 768px) {
    .hero-title {
        font-size: 2.5rem;
    }
    
    .hero-content {
        text-align: center;
        padding: 0 1rem;
        margin-bottom: 2.5rem;
    }
        
    .hero-buttons {
        justify-content: center;
    }
}

/* Mobiles (moins de 768px) */
@media (max-width: 767px) {
    .hero-title {
        font-size: 2rem;
    }
    
    .hero-content {
        text-align: center;
        padding: 0 1rem;
        margin-bottom: 2rem;
    }
        
    .hero-buttons {
        justify-content: center;
        flex-direction: column; /* éventuel empilement vertical */
    }
}
</style>

// src/pages/landing-page/HomeSection/HeroSection.jsx
import React, { useEffect, useRef } from 'react';
import AOS from 'aos';
import 'aos/dist/aos.css';
import './HeroSection.css';

const HeroSection = () => {
  const dashboardPreview = useRef(null);

  const handleMouseMove = (e) => {
    if (!dashboardPreview.current) return;
    const { clientX, clientY } = e;
    const { innerWidth, innerHeight } = window;

    const x = (clientX - innerWidth / 2) / 25;
    const y = (clientY - innerHeight / 2) / 25;

    dashboardPreview.current.style.transform =
      `perspective(1000px) rotateY(${x}deg) rotateX(${-y}deg)`;
  };

  useEffect(() => {
    AOS.init({
      duration: 1000,
      easing: 'ease-out',
      once: true
    });

    window.addEventListener('mousemove', handleMouseMove);

    // Cleanup event listener on component unmount
    return () => {
      window.removeEventListener('mousemove', handleMouseMove);
    };
  }, []);

  return (
    <section id="landingHero" className="d-flex align-items-center position-relative" style={{ paddingTop:100, width: 'max-content', margin: '0 auto' }} >
      {/* Background Animation */}
      <div className="hero-bg">
        <div className="gradient-blob blob-1"></div>
        <div className="gradient-blob blob-2"></div>
        <div className="gradient-blob blob-3"></div>
      </div>

      <div className="container position-relative">
        <div className="row align-items-center min-vh-100">
          {/* Text Content */}
          <div className="col-lg-6 hero-content" data-aos="fade-up">
            {/* Title */}
            <h3 className="hero-title" data-aos="fade-up" data-aos-delay="300">
              <span className="gradient-text">Nos solutions</span> adaptées
           pour votre
              <span className="highlight-text"> organisation</span>
            </h3>

            {/* Description */}
            <p className="hero-description">
                <span>
  Découvrez comment ERP INNOV peut transformer votre activité.
  Que vous soyez entrepreneur individuel, TPE/PME en croissance, grande entreprise, association ou administration, nous vous offrons des solutions adaptées qui permettent :
  </span><br />
  • <b>Réduction des coûts opérationnels</b> : Optimisez vos dépenses et améliorez votre rentabilité.<br />
  • <b>Optimisation de la gestion</b> : Optimisez vos dépenses et améliorez votre rentabilité.<br />
  • <b>Croissance accélérée</b> : Adoptez des outils performants pour soutenir votre développement.
</p>

            {/* CTA Buttons */}
            <div className="hero-buttons" data-aos="fade-up" data-aos-delay="500">
              <a href="/login" className="btn-primary">
                <span>En savoir plus, inscription gratuite</span>
                <i className="ri-arrow-right-line ms-2"></i>
              </a>
            </div>
          </div>

          {/* Dashboard Preview */}
          <div className="col-lg-6 hero-dashboard" data-aos="fade-left" data-aos-delay="300">
            <div className="dashboard-wrapper" ref={dashboardPreview}>
              <img 
                src="/assets/img/front-pages/landing-page/hero-dashboard-light.png"
                alt="Dashboard Preview"
                className="dashboard-image" 
              />

              {/* Stats Cards */}
              <div className="stats-card stats-card-1">
                <div className="stats-indicator success"></div>
                <span>+24% Croissance</span>
              </div>

              <div className="stats-card stats-card-2">
                <div className="stats-indicator primary"></div>
                <span>35% d'économies sur vos coûts</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default HeroSection;
